<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56fbf9d286422',
	'title' => 'Brand',
	'fields' => array (
		array (
			'key' => 'field_56fbf9e3a38e4',
			'label' => 'Image assets',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56fbfa0ea38e7',
			'label' => 'Favicon (.ico)',
			'name' => 'brand_fav_icon_ico',
			'type' => 'file',
			'instructions' => 'Please upload an .ico file here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.ico',
		),
		array (
			'key' => 'field_56fbfa61a38e8',
			'label' => 'Favicon (.png)',
			'name' => 'brand_fav_icon_png',
			'type' => 'image',
			'instructions' => 'Please upload a square icon at 600px by 600px. We\'re going to automatically shrink the image down to all the sizes we need.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.png',
		),
		array (
			'key' => 'field_56fbfad5a38e9',
			'label' => 'Favicon (wide, .png)',
			'name' => 'brand_fav_icon_wide_png',
			'type' => 'image',
			'instructions' => 'Upload an image that\'s at least 558px by 270px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.png',
		),
		array (
			'key' => 'field_56fbf9f7a38e5',
			'label' => 'Colors',
			'name' => '_copy',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56fbfb4ea38ea',
			'label' => 'Brand\'s Primary Color',
			'name' => 'brand_primary_color',
			'type' => 'color_picker',
			'instructions' => 'Enter the primary color of your brand. This will be used in a few places: 1. When someone bookmarks or pins your site on any Windows browsers, this will be the color of the tile. 2. When scrolling on some browsers, the color of the tab or overlay will be this color 3. This color might be used inside you theme for a variety of other things.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array (
			'key' => 'field_56fbfbeea38eb',
			'label' => 'Brand\'s Secondary Color',
			'name' => 'brand_secondary_color',
			'type' => 'color_picker',
			'instructions' => 'Enter the secondary color of your brand. This will be used in to complement the same places the primary color is going to be used.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#4a4a4a',
		),
		array (
			'key' => 'field_56fbfc17a38ec',
			'label' => 'Image Preloading background color',
			'name' => 'brand_image_preloading_color',
			'type' => 'color_picker',
			'instructions' => 'Enter the image preloading color of your brand. Before images are loaded, you&rsquo;ll see this as a block of color.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#d0d0d0',
		),
		array (
			'key' => 'field_56fbf9ffa38e6',
			'label' => 'Experience',
			'name' => '_copy',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56fbfd85a38f0',
			'label' => 'Do you want to enable the page builder?',
			'name' => 'enable_page_builder',
			'type' => 'true_false',
			'instructions' => 'Turning on the page builder will let you make pages in really flexible ways. ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Turn this feature on.',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56fbfc36a38ed',
			'label' => 'Do you want to enable caching?',
			'name' => 'enable_caching',
			'type' => 'true_false',
			'instructions' => 'Turning this on will store every page in a Wordpress transient after it&rsquo;s been compiled. This dramatically speeds up the site, but some pages will have caching. You can clear the cache by deleting transients by using a database optimizing plugin.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Turn this feature on.',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56fbfc96a38ee',
			'label' => 'Do you want to enable ajax?',
			'name' => 'enable_ajax',
			'type' => 'true_false',
			'instructions' => 'Turning ajax on means the site will load much faster between page, but if the site isn\'t coded for ajax you might run into issues.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Turn this feature on.',
			'default_value' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'These settings will let you change the site\'s branding, colors, and experience.',
));

endif;
