<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55f33ed61b053',
	'title' => 'SEO & Social Discovery',
	'fields' => array (
		array (
			'key' => 'field_56febfea48fd1',
			'label' => 'Heads up!',
			'name' => 'heads_up!',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'These settings completely override the global settings you have on the <a href="/wp-admin/admin.php?page=acf-options-seo">SEO</a> and <a href="/wp-admin/admin.php?page=acf-options-sdo">SDO</a> pages.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56fe9ca6373f7',
			'label' => 'SEO',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56fe9f35ec24c',
			'label' => 'Title',
			'name' => 'seo_page_title',
			'type' => 'text',
			'instructions' => '\'You can customize how the title looks here. <br /><br /> • <b>{title}</b> for the name of the current page, \' . get_the_title($_GET[\'post\']) . \'. <br /> • <b>{site_name}</b> or <b>{site_title}</b> for the name of the blog, \'.get_bloginfo(\'name\').\'.\'',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{title} • {site_title}',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56fe9f66ec24d',
			'label' => 'Description',
			'name' => 'seo_page_description',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56fe9f80ec24e',
			'label' => 'Keywords',
			'name' => 'seo_page_keywords',
			'type' => 'repeater',
			'instructions' => 'When choosing keywords for this page, try to have a good mix of general or specific (long-tail) keywords, to better target your audience. ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56fe9fafec24f',
			'min' => 1,
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Keyword',
			'sub_fields' => array (
				array (
					'key' => 'field_56fe9fafec24f',
					'label' => 'Keyword',
					'name' => 'keyword',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56fe9cc078ce8',
			'label' => 'Social Discovery',
			'name' => 'social_discovery',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55f33eeb3e73d',
			'label' => 'Image when shared',
			'name' => 'sdo_fallback_image',
			'type' => 'image',
			'instructions' => 'Upload an image at: <strong>1600px</strong> × <strong>800px</strong> high with a <strong>160px</strong> padding on the left and right margins.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56fda5218856d',
			'label' => '<h1>Twitter</h1>',
			'name' => 'h1twitterh1',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56fda4328856c',
			'label' => 'Twitter Card',
			'name' => 'sdo_twitter_card',
			'type' => 'select',
			'instructions' => 'Reference these items <a href="https://dev.twitter.com/cards/types/product" target="_blank">here</a>.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'None',
				'summary' => 'Summary',
				'summary_large_image' => 'Summary with a Large Image',
				'photo' => 'Photo',
				'gallery' => 'Gallery',
				'app' => 'App',
				'player' => 'Video Player',
				'product' => 'Product',
			),
			'default_value' => array (
				0 => 'none',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56fea30ed059e',
			'label' => 'Creator',
			'name' => 'sdo_twitter_card_creator',
			'type' => 'text',
			'instructions' => 'Add a valid Twitter handle - this would be the person who wrote this article',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fda4328856c',
						'operator' => '!=',
						'value' => 'none',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56fea3b8d059f',
			'label' => 'Labels & information',
			'name' => 'sdo_twitter_card_labels_and_data',
			'type' => 'repeater',
			'instructions' => 'This card supports up to four lists of information. ',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fda4328856c',
						'operator' => '==',
						'value' => 'product',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56fea3e8d05a0',
			'min' => 1,
			'max' => 4,
			'layout' => 'table',
			'button_label' => 'Add a Label',
			'sub_fields' => array (
				array (
					'key' => 'field_56fea3e8d05a0',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56fea3f3d05a1',
					'label' => 'Data',
					'name' => 'data',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56fea43cd05a2',
			'label' => 'Gallery',
			'name' => 'sdo_twitter_card_gallery',
			'type' => 'repeater',
			'instructions' => 'Galleries support up to 4 images. ',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fda4328856c',
						'operator' => '==',
						'value' => 'gallery',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 4,
			'layout' => 'table',
			'button_label' => 'Add an image',
			'sub_fields' => array (
				array (
					'key' => 'field_56fea43cd05a3',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'apple-square-76',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_56fea486d05a5',
			'label' => 'App Details',
			'name' => 'sdo_twitter_card_app_details',
			'type' => 'repeater',
			'instructions' => 'You\'ll need a country, and links if you want to add iPhone, iPad, or Google play links. ',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fda4328856c',
						'operator' => '==',
						'value' => 'app',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56fea49fd05a6',
			'min' => 1,
			'max' => 3,
			'layout' => 'table',
			'button_label' => 'Add a Platform',
			'sub_fields' => array (
				array (
					'key' => 'field_56fea49fd05a6',
					'label' => 'Platform',
					'name' => 'platform',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'iphone' => 'iPhone',
						'ipad' => 'iPad',
						'googleplay' => 'Google Play',
					),
					'default_value' => array (
					),
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_56fea50ed05a7',
					'label' => 'App Name',
					'name' => 'app_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56fea525d05a8',
					'label' => 'App ID',
					'name' => 'app_id',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56fea536d05a9',
					'label' => 'App URL',
					'name' => 'app_url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56fea66ed05aa',
			'label' => 'Video',
			'name' => 'sdo_twitter_card_app_video',
			'type' => 'repeater',
			'instructions' => 'Video player',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fda4328856c',
						'operator' => '==',
						'value' => 'player',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56fea69cd05af',
			'min' => 1,
			'max' => 1,
			'layout' => 'block',
			'button_label' => 'Add a Platform',
			'sub_fields' => array (
				array (
					'key' => 'field_56fea6d0d05b2',
					'label' => 'Player MP4 video',
					'name' => 'player_stream',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
				array (
					'key' => 'field_56fea72bd05b4',
					'label' => 'Player Vimeo Link',
					'name' => 'player_vimeo_link',
					'type' => 'url',
					'instructions' => 'You can use this if you have a pro account on Vimeo. Otherwise, please upload the video. ',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_56fda53ff123a',
			'label' => '<h1>Facebook</h1>',
			'name' => 'h1facebookh1',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56fda5a5f123b',
			'label' => 'Facebook	Story Type',
			'name' => 'sdo_facebook_story_type',
			'type' => 'select',
			'instructions' => 'Reference these items <a href="https://developers.facebook.com/docs/sharing/webmasters#media" target="_blank">here</a>.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'None',
				'article' => 'Article',
				'books.book' => 'Book',
				'books.author' => 'Book - Specific Author',
				'books.genre' => 'Book - Specific Genre',
				'business.business' => 'Business',
				'fitness.course' => 'Fitness - Course',
				'game.achievement' => 'Game - Specific Achievement',
				'music.album' => 'Music - Specific Album',
				'music.playlist' => 'Music - Specific Playlist',
				'music.radio_station' => 'Music - Specific Radio Station',
				'music.song' => 'Music - Specific Song',
				'place' => 'Place',
				'product' => 'a Standalone Product',
				'product.group' => 'a Family of Products',
				'product.item' => 'an Item in a Family of Products',
				'profile' => 'Facebook Profile',
				'restaurant.restaurant' => 'Restaurant',
				'restaurant.menu' => 'Restaurant - Menu',
				'restaurant.menu_item' => 'Restaurant - Menu Item',
				'restaurant.menu_section' => 'Restaurant - Menu section',
				'video.movie' => 'Video - Movie',
				'video.tv_show' => 'Video - TV Show',
				'video.episode' => 'Video - a single episode of a TV Show',
				'video.other' => 'Video - Other',
			),
			'default_value' => array (
				0 => 'none',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'post',
			),
		),
	),
	'menu_order' => -100,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;
